---

# https://github.com/bennojoy/nginx/blob/master/tasks/main.yml

- name: "Install nginx on CentOS6.8"
  hosts: nginxserver
  # remote_user: root
  become: True
  # get_fact: true
  # setup:
  # vars:
    # redhat_pkg:
    # - nginx
    # - python
  
  vars_files:
  # import vars files
    - vars/main.yml
    - defaults/main.yml
    
    
  tasks:
    - name: Install the selinux python module
      yum: name="libselinux-python"       
      # 使用 when 进行条件判断
      when: ansible_os_family == "RedHat"
      
    - name: install python
      # yum: name=python
      yum: name={{ item }} state=present
      # github原文中这里测试不通过
      # with_items: redhat_pkg  
      # 使用引号将变量括起来. ansible 2.2.0.0
      with_items: "{{ redhat_pkg }}"
      when: ansible_os_family == "RedHat"
      
    - name: Copy repo packages
      copy: src=epel.repo dest=/etc/yum.repos.d/epel_ansible.repo
      # 使用 and / or 进行条件连接
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

    - name: Install nginx packages
      yum: name=nginx state=present
      when: ansible_os_family == "RedHat"

    - name: Create the directories for site specific configuration
    
      # 01 单行写法
      file: path=/etc/nginx/{{ item }} state=directory owner=root group=root mode=0755
      
      # 02 换行写法
      # file: >
            # path=/etc/nginx/{{ item }} 
            # state=directory 
            # owner=root 
            # group=root 
            # mode=0755
            
      # 03 yaml 语法
      # file:
        # path: "/etc/nginx/{{ item }}"
        # state: directory 
        # owner: root 
        # group: root 
        # mode: 0755
        
      with_items:
        - "sites-available"
        - "sites-enabled"
        
    - name: Copy the nginx default site configuration file
      template: src=default.j2 dest=/etc/nginx/sites-available/default
      
    - name: Copy the site configuration file
      template: src=site.j2 dest="/etc/nginx/sites-available/{{ item.server.file_name }}.conf"
      # item 指代的为 nginx_sites
      with_items: "{{ nginx_sites }}"
      

